
import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { UserContextWrapper } from "../context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <nav className="flex sticky top-0 h-20 items-center text-md backdrop-blur-2xl text-[#E4E4E4] bg-[#5954542f] justify-between px-10">
          <div className="heading text-2xl">
            <h1>Superbody Gym</h1>
          </div>

          <div className="linksContainer flex gap-10">
            <Link href="/">Home</Link>
            <Link  href="/members">Members</Link>
            <Link href="/payment">Payments</Link>
          </div>
        </nav>

        <UserContextWrapper>
          {children}
        </UserContextWrapper>
      </body>
    </html>
  );
}