import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex h-20 items-center text-md backdrop-blur-2xl bg-gray-200/10 justify-between px-10 ">
          <div className="heading"><h1>Superbody Gym</h1></div>
          
          <div className="linksContainer flex gap-10 ">
            <Link  href="/">Home</Link>
            <Link href="/members">Members</Link>
            <Link href="/payment">Payments</Link>
            
          </div>
        </nav>

        {children}</body>
    </html>
  );
}
